import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { GoogleAnalytics } from "@next/third-parties/google";
import ThemeWrapper from "@/providers/ThemeWrapper";
import SessionProviders from "@/providers/SessionProviders";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Optional prefetch to avoid a client refetch/flicker
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProviders session={session}>
          <ThemeWrapper>
            <Header />
            {children}
          </ThemeWrapper>
        </SessionProviders>
        <GoogleAnalytics gaId="G-5ZN5XR28VX" />
      </body>
    </html>
  );
}
