export const initialCarState = {
  title: "",
  carMake: "",
  model: "",
  trim: "",
  year: 0,
  color: "",
  bodyType: "",
  condition: "",
  mileage: "",
  fuel: "",
  transmission: "",
  carLicense: false,
  insurance: "",
  carCustoms: false,
  regionalSpecs: "",
  engineSize: 0,
  batterySize: "",
  specifications: [],
  tireSize: "",
  interiorOptions: [],
  exteriorOptions: [],
  paymentMethod: "",
  price: 0,
  pricePerMonth: 0,
  purchasePrice: 0,
  shippingCost: 0,
  customsDuty: 0,
  repairCost: 0,
  totalLandedCost: 0,
  marketAverage: 0,
  precisionIndex: 0,
  vinNumber: "",
  paint: false,
  images: [],
  logoImage: "",
  importSource: "",
  titleStatus: "",
  auctionName: "",
  carSeerHistory: {
    clean: true,
    reportUrl: "",
    aiSummary: "",
    carseerRating: 0,
    previousOwners: 0,
    primaryDamage: "",
    annualLicenseFee: 0,
  },
  pages: [
    {
      title: "Luxury",
      intro: "",
      h2Title: "",
      blocks: [],
    },
    {
      title: "Technology",
      intro: "",
      h2Title: "",
      splide: [],
      blocks: [],
    },
    {
      title: "Comfort",
      intro: "",
      h2Title: "",
      blocks: [],
    },
    {
      title: "Performance",
      intro: "",
      h2Title: "",
      blocks: [],
    },
  ],
  lastPageDescription: "",
  extra: [],
};

export const mainSections = [
  { title: "Basic Information" },
  { title: "Options and Features" },
  { title: "Money Related Information" },
  { title: "Pages Information" },
  { title: "Assets & Extras" },
];

export const TEXT_BLOCK = "text";
export const CONTENT_BLOCK = "content";
